# Generated by Django 5.0 on 2024-01-11 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Memory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('slug', models.SlugField(unique=True)),
                ('date', models.DateTimeField()),
                ('updated', models.DateTimeField(auto_now=True)),
                ('image', models.ImageField(upload_to='images/')),
                ('context', models.CharField(choices=[('M', 'Maryama'), ('A', 'Arya'), ('T', 'Together'), ('F', 'Family')], default='T', max_length=2)),
            ],
            options={
                'verbose_name': 'Memory ✨',
                'verbose_name_plural': 'Memories ✨✨',
                'ordering': ['-date'],
            },
        ),
    ]
