# Generated by Django 5.0 on 2024-01-11 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='memory',
            name='video',
            field=models.FileField(default=None, upload_to='videos/'),
        ),
        migrations.AlterField(
            model_name='memory',
            name='image',
            field=models.ImageField(default=None, upload_to='images/'),
        ),
    ]
