# Generated by Django 5.0 on 2024-01-11 13:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_memory_video_alter_memory_image'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='memory',
            options={'ordering': ['-date'], 'verbose_name': 'Memory ✨', 'verbose_name_plural': 'Memories ✨'},
        ),
    ]
