# Generated by Django 5.0 on 2024-01-11 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_memory_context_alter_memory_video'),
    ]

    operations = [
        migrations.AlterField(
            model_name='memory',
            name='date',
            field=models.DateField(),
        ),
    ]
